Add contributing instructions
hacf-fr/Information pull request #4
Opened 2020-07-03 23:46 UTC by oncleben31

2020-07-05 09:49 UTC, Quentame requested changes
Some English to correct.

And some proportions

2020-07-05 09:49 UTC, Quentame commented on README.md
> +You will find guidelines for your contirbution in [CONTRIBUTING_EN.md](CONTRIBUTING_EN.md) file.
guidelines to contribute in the contributing file.

2020-07-05 09:49 UTC, Quentame commented on CONTRIBUTING_EN.md
> +availabel in the repository.
available

2020-07-05 09:49 UTC, Quentame commented on CONTRIBUTING.md
> +
On ne devrait pas aussi proposer une règle de nommage pour le nom des repos?

Genre pour une lib, on pourrait commencer ou terminer le nom par « api » ou « lib ».

Pour les custom component pareil mais avec « custom » ou « cc ».

Ça permettrait de mieux les retrouver dans les repos quand il commencera à en avoir beaucoup.

Exemples

Devant, tri par type
api-linky 
api-meteo_france
custom-linky 
custom-meteo_france
home-assistant-core

Derrière, tri par intégration:
home-assistant-core
linky-api 
linky-custom 
meteo_france-api
linky-custom

2020-07-05 09:49 UTC, Quentame commented on CONTRIBUTING.md
> +
On indiquerait pas une convention de nommage pour les branches ?

nom_integration/fonction

2020-07-05 21:09 UTC, oncleben31 commented on README.md
> +You will find guidelines for your contirbution in [CONTRIBUTING_EN.md](CONTRIBUTING_EN.md) file.
fix

2020-07-05 21:14 UTC, oncleben31 commented on CONTRIBUTING_EN.md
> +availabel in the repository.
fixed

2020-07-05 21:15 UTC, oncleben31 commented on CONTRIBUTING.md
> +
j'aime bien l'idée.

2020-07-05 21:52 UTC, oncleben31 commented on CONTRIBUTING.md
> +
J'ai ajouté un convention pour les lib, custom compoentns et carte lovelace.

2020-07-06 11:15 UTC, Quentame approved these changes

2020-07-06 11:15 UTC, merged